### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Korenn** [SpongePowered/noise#26]
Hey. Thanks for working on the library still and publishing new changes. That's greatly appreciated.

But wtf were you thinking pushing breaking changes to the repository under the same version number? It just broke our whole world generation project. We can't even revert to an older version because of this.

Please use the version number what it's intended for and bump it on uploads. Thanks!

**Comment by Zidane** [comment]
Broke your project in what way?

**Comment by Korenn** [comment]
You made fundamental changes to how the Module class works, so all our custom Modules no longer compile.

**Comment by Zidane** [comment]
Can you point to a particular diff for the breakage?

**Comment by Korenn** [comment]
Module.getSourceModuleCount() was made final so it can no longer be @Overridden, NoModuleException now needs a parameter.

Those are breaking changes

**Comment by Korenn** [comment]
Note that I don't mind these changes, just stick them in a new version number!

**Comment by Zidane** [comment]
https://github.com/SpongePowered/noise/commit/97fdd3b97f0a50962555004b737323ff940f324c#diff-487ccffc2d63d6ef3f660cbad0b1ec053b89d900531804619cacb435a447df4f

Was in this commit.

**Comment by gabizou** [comment]
> But wtf were you thinking pushing breaking changes to the repository under the same version number?

I'd like to note that those changes are on snapshots still, by no means are snapshots meant to be relied on as permanent/finalized/immune to breakages.

**Comment by Korenn** [comment]
> I'd like to note that those changes are on snapshots still, by no means are snapshots meant to be relied on as permanent/finalized/immune to breakages.
Any push to maven / nexus that breaks the API should always have a new version, even when it's a snapshot. There's zero reason you can't go from 2.0.0-SNAPSHOT to 2.0.1-SNAPSHOT. A trivial change that won't break the projects that are actually using this library (which supposedly was the idea of publishing it)

And it's been like this for so long now, that the word 'snapshot' is meaningless now. This is what people use, this is the released version.

**Comment by dualspiral** [comment]
> This is what people use, this is the released version.

Uhhh, no. _We_ decide when it's released, not our users because it's been this way for some time. 

> Any push to maven / nexus that breaks the API should always have a new version, even when it's a snapshot.

Nope. By definition it is subject to change and by using this software **you bear the risk of this changing with no notice**. See https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401

When we release 2.0.0 proper, _then_ you can assume stability. Not before.

If you _really_ want to use a pre-release version, you can select the version you want from https://repo.spongepowered.org/#browse/browse:maven-public:org%2Fspongepowered%2Fnoise%2F2.0.0-SNAPSHOT if you like. I advise you keep up with the snapshots though, because none of these builds will see any sort of support.

> There's zero reason you can't go from 2.0.0-SNAPSHOT to 2.0.1-SNAPSHOT

There's plenty of reason, actually, because we're following [semantic versioning](https://semver.org/). If we bumped to 2.0.1, then we're boxing ourselves into having to keep the API the same. We're not doing that.

I appreciate that you're wanting to use version 2 of our library, but it isn't released yet. Use the version 1.x series if you require stability. I believe there are a couple more changes that may need to be made before we release 2.0.0.

It's labeled a snapshot. The onus is on you to understand things might still change.

**Comment by Zidane** [comment]
With dual's comments, I see no need for further discussion. SNAPSHOTs have well defined meaning in maven versioning guidelines.

I would recommend to the OP to choose carefully in the future when targeting production code against unreleased, unstable, library code.
